#pragma once
std::vector<Mesh> meshes;
std::vector<InstantableMesh> fireAccesiories;
std::vector<InstantableMesh> flames;
std::vector<ParticleGenerator> smokes;
std::vector<NamedMesh> rotatingNamedMeshes;
std::vector<CFont> fonts;
std::vector<PointLightShadow> pointLightShadows;
std::vector<CollidingMesh> unreachablePlaces;
std::vector<CollidingMesh> collectMeshes;
std::vector<Mesh> unr_meshes;
std::vector<Mesh> collect_meshes;